version: '2'
services:
    serviceplan-app:
        image: serviceplan
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://serviceplan-postgresql:5432/serviceplan
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    serviceplan-postgresql:
        extends:
            file: postgresql.yml
            service: serviceplan-postgresql
